### ISSUE TITLE
OS Error: A required privilege is not held by the client.

### ISSUE THREAD

**Issue by baranmukry** [delay/flutter_firebase_auth_starter#5]
OS Error: A required privilege is not held by the client.

**Comment by delay** [comment]
https://firebase.google.com/docs/flutter/setup?platform=android Maybe it has something to do with your firebase setup.  Also the firebase auth libraries have changed a lot since I released this version so probably something will need to change there.  Basically I no longer maintain this project as I am not currently coding in flutter any longer.  Also this project has been redone with getX here. https://github.com/delay/flutter_starter I haven't had any reports of this error on that version.
